export default [
  {
    name: 'baskets',
    value: 1,
    max: 10,
    ratio: 1,
    prices: { wood: 10 },
    unlockRequirements: { wood: 5 },
    tab: 'forest',
    effects: [
      { type: '+max', payload: { name: 'food', value: 100 } },
      { type: '+max', payload: { name: 'wood', value: 10 } },
    ],
  },
  {
    name: 'hut',
    value: 1,
    prices: { wood: 50 },
    ratio: 1,
    max: 5,
    unlockRequirements: { wood: 25 },
    tab: 'forest',
    effects: [{ type: '+max', payload: { name: 'folks', value: 1 } }],
  },
  {
    name: 'plot',
    tab: 'field',
    max: 10,
    value: 0,
    ratio: 1,
    prices: { food: 500, wood: 100 },
    effects: [{ type: '+max', payload: { name: 'farm', value: 1 } }],
  },
  {
    name: 'silo',
    tab: 'field',
    max: 10,
    value: 0,
    ratio: 1,
    prices: { wood: 100 },
    unlockRequirements: { food: 1500 },
    effects: [{ type: '+max', payload: { name: 'food', value: 250 } }],
  },
]
