export default [
  {
    name: 'baskets',
    value: 0,
    max: 10,
    ratio: 1,
    prices: { wood: 10 },
    unlockRequirements: { wood: 5 },
    tab: 'shelter',
    effects: [
      { type: 'maxResource', payload: { name: 'food', value: 50 } },
      { type: 'maxResource', payload: { name: 'wood', value: 10 } },
    ],
  },
  {
    name: 'hut',
    value: 0,
    prices: { wood: 50 },
    ratio: 1,
    max: 1,
    unlockRequirements: { wood: 25 },
    tab: 'shelter',
    effects: [{ type: 'maxResource', payload: { name: 'folks', value: 1 } }],
  },
  {
    name: 'lumbermill',
    tab: 'shelter',
    value: 0,
    prices: { wood: 200 },
    unlockRequirements: { wood: 200 },
    effects: [{ type: 'maxResource', payload: { name: 'wood', value: 100 } }],
  },
  {
    name: 'farm',
    tab: 'field',
    value: 0,
    prices: { wood: 2 },
    unlockRequirements: { wood: 1 },
    effects: [{ type: 'maxResource', payload: { name: 'food', value: 100 } }],
  },
]
