export default [
  {
    name: 'hunt+',
    tab: 'forest',
    labels: ['spear'],
    max: 1,
    prices: { wood: 1 },
    unlockRequirements: { wood: 0.5 },
    value: 0,
    effects: [{ type: 'improveJob', payload: { name: 'hunt', value: 1.334 } }],
  },
  {
    name: 'scavenge+',
    labels: ['rucksack', 'bigger rucksack'],
    max: 2,
    tab: 'forest',
    ratio: 8,
    prices: { wood: 4 },
    unlockRequirements: { wood: 2 },
    value: 0,
    effects: [{ type: 'improveJob', payload: { name: 'scavenge', value: 5 } }],
  },
  {
    name: 'farm+',
    labels: ['fertilizer', 'bigger rucksack'],
    max: 2,
    tab: 'field',
    ratio: 8,
    prices: { food: 1500, wood: 250 },
    unlockRequirements: { wood: 2 },
    value: 0,
    effects: [{ type: 'improveJob', payload: { name: 'farm', value: 1.5 } }],
  },
]
