export default [
  {
    name: 'hunter+',
    tab: 'forest',
    labels: ['spear'],
    max: 1,
    prices: { wood: 1 },
    unlockRequirements: { wood: 0.5 },
    value: 0,
    effects: [
      { type: 'improveJob', payload: { name: 'hunter', value: 1.334 } },
    ],
  },
  {
    name: 'scavenger+',
    labels: ['rucksack', 'bigger rucksack'],
    max: 2,
    tab: 'forest',
    ratio: 8,
    prices: { wood: 4 },
    unlockRequirements: { wood: 2 },
    value: 0,
    effects: [{ type: 'improveJob', payload: { name: 'scavenger', value: 5 } }],
  },
  {
    name: 'farmer+',
    labels: ['fertilizer', 'bigger rucksack'],
    max: 2,
    tab: 'field',
    ratio: 8,
    prices: { food: 1500, wood: 250 },
    unlockRequirements: { plot: 3 },
    value: 0,
    effects: [{ type: 'improveJob', payload: { name: 'farmer', value: 1.5 } }],
  },
  {
    name: 'lumberjack+',
    labels: ['iron axe', 'steel axe'],
    max: 2,
    tab: 'forest',
    ratio: 8,
    prices: { stone: 10, wood: 100 },
    unlockRequirements: { stone: 1 },
    value: 0,
    effects: [
      { type: 'improveJob', payload: { name: 'lumberjack', value: 1.5 } },
    ],
  },
]
